server:
  port: 9080

spring:
  r2dbc:
    url: r2dbc:mysql://root:9999@localhost:3206/founding?useUnicode=true&characterEncoding=utf8
    pool:
      max-size: 10
      validation-query: SELECT 1
logging:
  level:
    org.springframework.r2dbc: DEBUG
